travis:
  secure:
    BINSTAR_TOKEN: yAagxKk5ah6yeNR4c/GI9PDgcj1ykqjBo8yl2egj7ShAiXhSc+Pc1Ooux9XV0tf5+XMBvbhgD0Vdt2tV4wGArudrmInlf9XL1POtsLUdunD6Bx8UYcDfRodkPVXCwzwT/C9s5ht+SM2JaAMTrFPi5ww5ov/va3W3uA7Pb+mpJWueNANX2unbjCSvdAs2bFQ8EYqut9wOJimzGLvq9FtKKqV8CqF3pkxiysHl4Yk3dNHBeB7XmNpMHJlihRQN0kx0JRxzepoB6eX0126WZiVIj1l3M5pFsoTJL9rl2yZiSbgpbv7dx2PKfTORxIu+tt3tf609rmECmXMja6FmuEHzDGatid4a0wEye0oBuv5mY+OaU9DVYXRETk9jdpL3jlCd/cXmRYJAqho7lKHSfFuY9Mnf3ZJvGcXOBQNWlbo4KyAHcmjF1cwDGz6Eaq8vAlr9g4S/VatooEdP+XZTd5V8jzDJNltHudPjw/6dwLRMYNuhWrGtNKWw9H0cS0gQbupscSjT91gfe+zVd6g1vwrnJujVstweohUcZKaJTaxMXCuDE8rfKF2JpFlm6WpxRzzUzJIKvt95yP1KzAiQHkuBcACxV2oaj872BA44E4Nx2Wms1rvZMMDpZ/sUjpubWAQVovP7Q09nQ7S+zEXLboBfDiS6f3ZXpi3NIdsPpML2p60=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
