travis:
  secure:
    BINSTAR_TOKEN: LjH4rBEEf+cD/qCj+OuOWSIKb7ge8E0XoNwqPzF7zlEkqhdqeKtTZFUMh8a5kQG0VY6DH/1f5iqaRxTZOo2mm57onIta7TVODAMpTMsoA5cDdZDfPbx3uJ8ZFWOUIGZXb1VUMYPRaLJS93BJ0uuYTmtwERq0VNvqJoOmiL/Fy/BnuiAQJ08qtIGNvR+tVqvQ4jrFUf+V8nO5jidnuT+0pCW3ydYcVmagtpDcD/5MV5fHulIxZTclaPrU5Mcrey23C9o+Fvt591mFmsNT3PLZcsbMtoqDhtkj25CcGfQSZdGH/P2pIrP8FoN8O6v1+Jxdeztwb7qUKZXhSOabbPpc5i/1Z64QMTEOFF5bSri/fWdKC/GPYS+wLB1V95uFh2RSWqgDk0U6FszfHhilMIMdSG+juO2M2fOEf/4452T6di4a3Ua+ugGeFfQkJCKAVRWWgdg7EV507FGBWOrJc1DKADSvSl+jaO2Oqyz9B+kyDOKPchU6ujbHD4R8og3tolAfzffbdGwBJYsNKJ54fL29/+UOg43ywCWPtnb/DuLpcqJWlhj11RAM4VyKKuGQc7cQwYjNjaSJx+Q9uDsWmzWd5Zmp0P9VMl4ntNaXSbYigBmYD53tYvhBSHpN2lWEdrxWdUjcHZlBXNMRmxiJOruuQq8OHlxvx2NKDzITtd+AKZs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
